use std::fs::File;
use std::io::Write;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::models::SpotifyTrack;

#[derive(Debug, thiserror::Error)]
pub enum CueError {
    #[error("Cannot generate CUE sheet without tracks")]
    EmptyTrackList,

    #[error("Invalid track number '{0}': Track numbers must be between 1 and 99")]
    InvalidTrackNumber(u32),

    #[error("Invalid CUE time format '{0}': expected MM:SS:FF")]
    InvalidTimeFormat(String),

    #[error("IO error writing CUE sheet: {0}")]
    Io(#[from] std::io::Error),
}

/// Represents a single audio track in a Red Book CUE sheet
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TrackAudio {
    pub track_number: u32,
    pub title: String,
    pub performer: String,
    pub file_name: String,
    pub isrc: Option<String>,
    pub pregap: Option<String>,
    pub index01: Option<String>,
}

impl TrackAudio {
    pub fn new(
        track_number: u32,
        title: impl Into<String>,
        performer: impl Into<String>,
        file_name: impl Into<String>,
    ) -> Self {
        Self {
            track_number,
            title: title.into(),
            performer: performer.into(),
            file_name: file_name.into(),
            isrc: None,
            pregap: if track_number == 1 {
                Some("00:02:00".to_string())
            } else {
                None
            },
            index01: Some("00:00:00".to_string()),
        }
    }

    /// Creates a `TrackAudio` from a `SpotifyTrack` and associated WAV file name/path
    pub fn from_spotify_track(track: &SpotifyTrack, file_name: &str) -> Self {
        let performer = if track.artists.is_empty() {
            "Unknown Artist".to_string()
        } else {
            track.artists.join(", ")
        };

        Self {
            track_number: track.track_number,
            title: track.title.clone(),
            performer,
            file_name: file_name.to_string(),
            isrc: track.isrc.clone(),
            pregap: if track.track_number == 1 {
                Some("00:02:00".to_string())
            } else {
                None
            },
            index01: Some("00:00:00".to_string()),
        }
    }

    pub fn with_isrc(mut self, isrc: impl Into<String>) -> Self {
        self.isrc = Some(isrc.into());
        self
    }

    pub fn with_pregap(mut self, pregap: impl Into<String>) -> Self {
        self.pregap = Some(pregap.into());
        self
    }
}

/// Complete CUE Sheet descriptor
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct CueSheet {
    pub album_title: Option<String>,
    pub album_performer: Option<String>,
    pub tracks: Vec<TrackAudio>,
}

impl CueSheet {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_album_info(
        album_title: Option<impl Into<String>>,
        album_performer: Option<impl Into<String>>,
        tracks: Vec<TrackAudio>,
    ) -> Self {
        Self {
            album_title: album_title.map(Into::into),
            album_performer: album_performer.map(Into::into),
            tracks,
        }
    }

    /// Renders the CUE sheet as a standard Red Book compliant string with CD-Text
    pub fn to_cuesheet_string(&self) -> Result<String, CueError> {
        if self.tracks.is_empty() {
            return Err(CueError::EmptyTrackList);
        }

        let mut out = String::new();
        out.push_str("REM Generated by SpotyBurn (Red Book CD-DA compliant)\n");

        if let Some(performer) = &self.album_performer {
            out.push_str(&format!("PERFORMER \"{}\"\n", sanitize_cd_text(performer)));
        }
        if let Some(title) = &self.album_title {
            out.push_str(&format!("TITLE \"{}\"\n", sanitize_cd_text(title)));
        }

        for track in &self.tracks {
            if track.track_number < 1 || track.track_number > 99 {
                return Err(CueError::InvalidTrackNumber(track.track_number));
            }

            out.push_str(&format!("FILE \"{}\" WAVE\n", track.file_name));
            out.push_str(&format!("  TRACK {:02} AUDIO\n", track.track_number));
            out.push_str(&format!(
                "    TITLE \"{}\"\n",
                sanitize_cd_text(&track.title)
            ));
            out.push_str(&format!(
                "    PERFORMER \"{}\"\n",
                sanitize_cd_text(&track.performer)
            ));

            if let Some(isrc) = &track.isrc {
                let clean_isrc = sanitize_isrc(isrc);
                if !clean_isrc.is_empty() {
                    out.push_str(&format!("    ISRC {}\n", clean_isrc));
                }
            }

            if let Some(pregap) = &track.pregap {
                out.push_str(&format!("    PREGAP {}\n", pregap));
            }

            let index01 = track.index01.as_deref().unwrap_or("00:00:00");
            out.push_str(&format!("    INDEX 01 {}\n", index01));
        }

        Ok(out)
    }

    /// Writes the rendered CUE sheet to a file on disk
    pub fn write_to_file(&self, output_cue: &Path) -> Result<(), CueError> {
        let content = self.to_cuesheet_string()?;
        if let Some(parent) = output_cue.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let mut file = File::create(output_cue)?;
        file.write_all(content.as_bytes())?;
        Ok(())
    }
}

/// Sanitizes CD-Text fields by replacing double quotes with single quotes
/// and removing non-printable control characters.
pub fn sanitize_cd_text(text: &str) -> String {
    text.chars()
        .filter(|c| !c.is_control() || *c == '\t')
        .map(|c| if c == '"' { '\'' } else { c })
        .collect::<String>()
        .trim()
        .to_string()
}

/// Normalizes ISRC to uppercase alphanumeric characters without hyphens or spaces
pub fn sanitize_isrc(isrc: &str) -> String {
    isrc.chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .collect::<String>()
        .to_ascii_uppercase()
}

/// Converts a sector count into the Red Book CUE time string format `MM:SS:FF`
/// (75 frames per second).
pub fn sectors_to_cuesheet_time(sectors: u64) -> String {
    let frames = sectors % 75;
    let total_seconds = sectors / 75;
    let seconds = total_seconds % 60;
    let minutes = total_seconds / 60;
    format!("{:02}:{:02}:{:02}", minutes, seconds, frames)
}

/// Parses a Red Book CUE time string format `MM:SS:FF` into the total number of sectors.
pub fn cuesheet_time_to_sectors(time_str: &str) -> Result<u64, CueError> {
    let parts: Vec<&str> = time_str.split(':').collect();
    if parts.len() != 3 {
        return Err(CueError::InvalidTimeFormat(time_str.to_string()));
    }

    let minutes: u64 = parts[0]
        .parse()
        .map_err(|_| CueError::InvalidTimeFormat(time_str.to_string()))?;
    let seconds: u64 = parts[1]
        .parse()
        .map_err(|_| CueError::InvalidTimeFormat(time_str.to_string()))?;
    let frames: u64 = parts[2]
        .parse()
        .map_err(|_| CueError::InvalidTimeFormat(time_str.to_string()))?;

    if seconds >= 60 || frames >= 75 {
        return Err(CueError::InvalidTimeFormat(time_str.to_string()));
    }

    let total_seconds = minutes * 60 + seconds;
    Ok(total_seconds * 75 + frames)
}

/// Generates a CUE sheet from a slice of `TrackAudio` and writes it to `output_cue`.
/// Matches interface in spec 3.2.
pub fn generate_cuesheet(tracks: &[TrackAudio], output_cue: &Path) -> Result<(), CueError> {
    let sheet = CueSheet {
        album_title: None,
        album_performer: None,
        tracks: tracks.to_vec(),
    };
    sheet.write_to_file(output_cue)
}

/// Generates a CUE sheet with optional album title and artist metadata.
pub fn generate_cuesheet_with_album(
    album_title: Option<&str>,
    album_performer: Option<&str>,
    tracks: &[TrackAudio],
    output_cue: &Path,
) -> Result<(), CueError> {
    let sheet = CueSheet {
        album_title: album_title.map(String::from),
        album_performer: album_performer.map(String::from),
        tracks: tracks.to_vec(),
    };
    sheet.write_to_file(output_cue)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_track_audio_from_spotify_track() {
        let track = SpotifyTrack {
            id: "t1".to_string(),
            title: "One More Time".to_string(),
            artists: vec!["Daft Punk".to_string()],
            album: "Discovery".to_string(),
            duration_ms: 320000,
            track_number: 1,
            isrc: Some("FRZ030000010".to_string()),
        };

        let audio = TrackAudio::from_spotify_track(&track, "track01.wav");
        assert_eq!(audio.track_number, 1);
        assert_eq!(audio.title, "One More Time");
        assert_eq!(audio.performer, "Daft Punk");
        assert_eq!(audio.file_name, "track01.wav");
        assert_eq!(audio.isrc.as_deref(), Some("FRZ030000010"));
        // Track 1 must have PREGAP 00:02:00
        assert_eq!(audio.pregap.as_deref(), Some("00:02:00"));
        assert_eq!(audio.index01.as_deref(), Some("00:00:00"));

        let track2 = SpotifyTrack {
            id: "t2".to_string(),
            title: "Aerodynamic".to_string(),
            artists: vec!["Daft Punk".to_string()],
            album: "Discovery".to_string(),
            duration_ms: 212000,
            track_number: 2,
            isrc: None,
        };
        let audio2 = TrackAudio::from_spotify_track(&track2, "track02.wav");
        assert_eq!(audio2.track_number, 2);
        // Track 2 must not have a default PREGAP
        assert_eq!(audio2.pregap, None);
    }

    #[test]
    fn test_cuesheet_rendering() {
        let tracks = vec![
            TrackAudio {
                track_number: 1,
                title: "Track \"One\"".to_string(),
                performer: "Artist A".to_string(),
                file_name: "track01.wav".to_string(),
                isrc: Some("US-RC1-76-07839".to_string()),
                pregap: Some("00:02:00".to_string()),
                index01: Some("00:00:00".to_string()),
            },
            TrackAudio {
                track_number: 2,
                title: "Track Two".to_string(),
                performer: "Artist B".to_string(),
                file_name: "track02.wav".to_string(),
                isrc: None,
                pregap: None,
                index01: Some("00:00:00".to_string()),
            },
        ];

        let sheet =
            CueSheet::with_album_info(Some("Best Hits 2026"), Some("Various Artists"), tracks);

        let content = sheet.to_cuesheet_string().expect("Generating CUE string");

        // Verify CD-Text and structure
        assert!(content.contains("PERFORMER \"Various Artists\""));
        assert!(content.contains("TITLE \"Best Hits 2026\""));
        assert!(content.contains("FILE \"track01.wav\" WAVE"));
        assert!(content.contains("  TRACK 01 AUDIO"));
        assert!(content.contains("    TITLE \"Track 'One'\"")); // Double quotes sanitized to single
        assert!(content.contains("    PERFORMER \"Artist A\""));
        assert!(content.contains("    ISRC USRC17607839")); // Sanitized without hyphens
        assert!(content.contains("    PREGAP 00:02:00"));
        assert!(content.contains("    INDEX 01 00:00:00"));

        assert!(content.contains("FILE \"track02.wav\" WAVE"));
        assert!(content.contains("  TRACK 02 AUDIO"));
        assert!(content.contains("    TITLE \"Track Two\""));
        assert!(content.contains("    PERFORMER \"Artist B\""));
        assert!(!content.contains(
            "TRACK 02 AUDIO\n    TITLE \"Track Two\"\n    PERFORMER \"Artist B\"\n    PREGAP"
        ));
    }

    #[test]
    fn test_cuesheet_time_conversions() {
        // 0 sectors -> 00:00:00
        assert_eq!(sectors_to_cuesheet_time(0), "00:00:00");
        assert_eq!(cuesheet_time_to_sectors("00:00:00").unwrap(), 0);

        // 75 sectors = 1 second -> 00:01:00
        assert_eq!(sectors_to_cuesheet_time(75), "00:01:00");
        assert_eq!(cuesheet_time_to_sectors("00:01:00").unwrap(), 75);

        // 150 sectors = 2 seconds (pregap) -> 00:02:00
        assert_eq!(sectors_to_cuesheet_time(150), "00:02:00");
        assert_eq!(cuesheet_time_to_sectors("00:02:00").unwrap(), 150);

        // 74 frames (last frame of 0th second) -> 00:00:74
        assert_eq!(sectors_to_cuesheet_time(74), "00:00:74");
        assert_eq!(cuesheet_time_to_sectors("00:00:74").unwrap(), 74);

        // 80 minutes audio CD capacity in sectors: 80 * 60 * 75 = 360,000 sectors
        assert_eq!(sectors_to_cuesheet_time(360000), "80:00:00");
        assert_eq!(cuesheet_time_to_sectors("80:00:00").unwrap(), 360000);

        // Invalid time formats
        assert!(cuesheet_time_to_sectors("00:00").is_err());
        assert!(cuesheet_time_to_sectors("00:60:00").is_err()); // seconds >= 60
        assert!(cuesheet_time_to_sectors("00:00:75").is_err()); // frames >= 75
        assert!(cuesheet_time_to_sectors("invalid").is_err());
    }

    #[test]
    fn test_write_cuesheet_to_file() {
        let temp_dir = std::env::temp_dir();
        let cue_path = temp_dir.join("test_cd.cue");

        let tracks = vec![TrackAudio::new(1, "Intro", "Artist", "01.wav")];
        generate_cuesheet(&tracks, &cue_path).expect("Generating cuesheet file");

        let read_back = std::fs::read_to_string(&cue_path).expect("Reading back cuesheet");
        assert!(read_back.contains("FILE \"01.wav\" WAVE"));
        assert!(read_back.contains("  TRACK 01 AUDIO"));
        assert!(read_back.contains("    PREGAP 00:02:00"));

        let _ = std::fs::remove_file(cue_path);
    }

    #[test]
    fn test_empty_tracklist_error() {
        let empty_tracks: Vec<TrackAudio> = vec![];
        let sheet = CueSheet {
            album_title: None,
            album_performer: None,
            tracks: empty_tracks,
        };
        assert!(matches!(
            sheet.to_cuesheet_string(),
            Err(CueError::EmptyTrackList)
        ));
    }

    #[test]
    fn test_invalid_track_number_error() {
        let tracks = vec![TrackAudio::new(0, "Invalid Track", "Artist", "00.wav")];
        let sheet = CueSheet {
            album_title: None,
            album_performer: None,
            tracks,
        };
        assert!(matches!(
            sheet.to_cuesheet_string(),
            Err(CueError::InvalidTrackNumber(0))
        ));

        let tracks_100 = vec![TrackAudio::new(100, "Too High", "Artist", "100.wav")];
        let sheet_100 = CueSheet {
            album_title: None,
            album_performer: None,
            tracks: tracks_100,
        };
        assert!(matches!(
            sheet_100.to_cuesheet_string(),
            Err(CueError::InvalidTrackNumber(100))
        ));
    }
}
